// packages/react-app/src/App.jsx
import React, { useEffect } from "react";
import logo from "./assets/logo.png";
import "./index.css";

const App = () => {
  useEffect(() => {
    window.dispatchEvent(new CustomEvent("loaded", { detail: "reactApp" }))
  }, [])

  return (
    <div className="row">
      <img className="logo" src={logo} />
      <span className="framework-name">React App</span>
    </div>
  );
}

export default App;

// packages/vue-app/src/App.vue
<script>
  export default {
    mounted() {
      this.$nextTick(function () {
        window.dispatchEvent(new CustomEvent("loaded", { detail: "vueApp" }));
      })
    }
  }
</script>

<style>
  @import './index.css';
</style>

<template>
  <div class="row">
    <img class="logo" :src="require('./assets/logo.png')" />
    <span class="framework-name">Vue App</span>
  </div>
</template>
