// packages/react-app/src/App.jsx
import React, { useEffect } from "react";
import logo from "./assets/logo.png";
import "./index.css";

const App = () => {
  useEffect(() => {
    window.dispatchEvent(new CustomEvent("loaded", { detail: "reactApp" }))
  }, [])

  return (
    <div className="row">
      <img className="logo" src={logo} />
      <span className="framework-name">React App</span>
    </div>
  );
}

export default App;

// packages/svelte-app/src/App.svelte
<script>
  import logo from "./assets/logo.png";
  import "./index.css";
  import { onMount } from "svelte";
  let name = "Svelte App";

  onMount(() => {
    window.dispatchEvent(new CustomEvent("loaded", { detail: "svelteApp" }));
  });
</script>

<main>
  <div class="row">
    <img alt="logo" src={logo} class="logo" />
    <span class="framework-name">
      {name}
    </span>
  </div>
</main>
